language: php

branches:
  only:
    - master
    - develop
    - /^(bugfix|feature)\/.*$/

php:
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - MAGENTO_VERSION="magento-ce-2.0.0" DB=mysql INSTALL_SAMPLE_DATA=0
  global:
    secure: "CJnQ2lmhXcHSuKor8RtjjeUEyUyFRCiezwdn6loy+IWQF3q+o6Tt36MOV+2V3/yG6p+EcUQXnphtdq11m86GSUVDqbOsa8aJLtdv+v+UuPG+0wBd0/akvTcZqeXb52dT2F1g6RwgZIh3fxHsQkXavrirILA39GZZdAaX7Ct49sQ="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: BUILDSH=1
      script: ./build.sh
    - php: 5.6
      env: BUILDSH=1
      script: ./build.sh
    - php: 7.0
      env: BUILDSH=1
      script: ./build.sh
    - php: 7.0
      env: LINTSH=1
      script: find {src,tests} -name "*.php" ! -path '*/String.php' -print0 | xargs
        -0 -n1 -P8 php -l | grep -v '^No syntax errors detected'; test $? -eq 1

  allow_failures:
    - php: 7.0
      env: MAGENTO_VERSION="magento-ce-2.0.0-rc" DB=mysql INSTALL_SAMPLE_DATA=0

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction --ignore-platform-reqs

before_script:
  - source ./build/travis/before_script.sh

script:
  - vendor/bin/phpunit --debug
