language: php

branches:
  only:
    - master
    - develop
    - /^(bugfix|feature)\/.*$/

php:
  - 5.5
  - 5.6

env:
  - MAGENTO_VERSION="magento-ce-2.0.0-rc" DB=mysql INSTALL_SAMPLE_DATA=0 COVERAGE=10

matrix:
  fast_finish: true

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction --ignore-platform-reqs

before_script:
  - source ./build/travis/before_script.sh

script:
  - vendor/bin/phpunit --debug
  - php dev/tests/check-coverage.php clover.xml ${COVERAGE}