language: php

branches:
  only:
    - develop

php:
  - 5.4
  - 5.5

env:
  - MAGENTO_VERSION="magento-ce-2.0.0.0-dev-beta1" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=10

matrix:
  fast_finish: true

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `magento_travis`;'
  - export N98_MAGERUN2_TEST_MAGENTO_ROOT="./${MAGENTO_VERSION}"
  - bin/n98-magerun2 install --magentoVersionByName="${MAGENTO_VERSION}" --installationFolder="./${MAGENTO_VERSION}" --dbHost=localhost --dbUser=root --dbPass='' --dbName="magento_travis" --installSampleData=${INSTALL_SAMPLE_DATA} --useDefaultConfigParams=yes --baseUrl="http://travis.magento.local/"

script:
  - vendor/bin/phpunit
  - php dev/tests/check-coverage.php clover.xml ${COVERAGE}