language: php

branches:
  only:
    - master
    - develop
    - /^(bugfix|feature)\/.*$/

php:
  - 5.5
  - 5.6

env:
  - MAGENTO_VERSION="magento-ce-2.0.0-rc" DB=mysql INSTALL_SAMPLE_DATA=0 COVERAGE=10

matrix:
  fast_finish: true
  include:
    # Run the build script with an older PHP version
    - php: 5.5
      env: BUILDSH=1
      script: ./build.sh

    # Run the build script with a recent PHP version
    - php: 5.6
      env: BUILDSH=1
      script: ./build.sh

    # Lint PHP code with PHP 7.0
    - php: 7.0
      env: LINTSH=1
      script: find {src,tests} -name "*.php" ! -path '*/String.php' -print0 | xargs -0 -n1 -P8 php -l | grep -v '^No syntax errors detected'; test $? -eq 1

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction --ignore-platform-reqs

before_script:
  - source ./build/travis/before_script.sh

script:
  - vendor/bin/phpunit --debug
  - php tests/check-coverage.php clover.xml ${COVERAGE}
