application:
  check-root-user: true

twig:
  baseDirs:

plugin:
  folders:
    - /usr/local/share/n98-magerun/modules

helpers:
  database: N98\Util\Console\Helper\DatabaseHelper
  dialog: Composer\Command\Helper\DialogHelper
  parameter: N98\Util\Console\Helper\ParameterHelper
  table: N98\Util\Console\Helper\TableHelper

script:
  folders:
    - /usr/local/share/n98-magerun/scripts

init:
  code: admin
  type: store
  options: []

detect:
  subFolders:
    - web
    - www
    - htdocs
    - public
    - pub
    - webroot
    - web-root
    - wwwroot

event:
  subscriber:
    - N98\Magento\EventSubscriber
    - N98\Magento\Command\ComposerWrapper\EventSubscriber

commands:
  customCommands:
    - N98\Magento\Command\System\InfoCommand
    - N98\Magento\Command\System\Store\ListCommand
    - N98\Magento\Command\System\Website\ListCommand
    - N98\Magento\Command\Indexer\ListCommand
    - N98\Magento\Command\Installer\InstallCommand

  disabled:
    - dummy

  aliases: []

  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: magento-ce-2.0.0.0-dev-beta1
        version: 0.1.0-beta1
        source:
          url: https://github.com/magento/magento2.git
          type: git
          reference: master
        extra:
          sample-data:
            magento/sample-data: "0.42.0-beta1"
            magento/sample-data-media: "0.42.0-beta1"

    installation:
      pre-check:
        php:
          extensions:
            - pdo_mysql
            - spl
            - dom
            - simplexml
            - mcrypt
            - hash
            - curl
            - iconv
            - ctype
            - gd

      defaults:
        currency: EUR
        locale: de_DE
        timezone: Europe/Berlin
        use_secure: no
        use_rewrites: yes
        session_save: files
        admin_username: admin
        admin_firstname: John
        admin_lastname: Doe
        admin_password: password123
        admin_frontname: admin
        admin_email: john.doe@example.com
        encryption_key: