application:
  check-root-user: true

twig:
  baseDirs:

plugin:
  folders:
    - /usr/local/share/n98-magerun/modules

helpers:
  database: N98\Util\Console\Helper\DatabaseHelper
  dialog: Composer\Command\Helper\DialogHelper
  parameter: N98\Util\Console\Helper\ParameterHelper
  table: N98\Util\Console\Helper\TableHelper

script:
  folders:
    - /usr/local/share/n98-magerun/scripts

init:
  code: admin
  type: store
  options: []

detect:
  subFolders:
    - web
    - www
    - htdocs
    - public
    - pub
    - webroot
    - web-root
    - wwwroot

event:
  subscriber:
    - N98\Magento\EventSubscriber
    - N98\Magento\Command\ComposerWrapper\EventSubscriber

commands:
  customCommands:
    - N98\Magento\Command\System\InfoCommand

  aliases: []
