---
name: Deploy

on:
  push:
    branches:
      - develop
      - deploy
    tags:
      # only tags with semver format
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-signed-phar-file:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:2
          php-version: '7.4'

      - name: Checkout HEAD
        uses: actions/checkout@v3.6.0

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create phar
        run: bash ./build.sh

      - name: Run phar file
        run: php n98-magerun2.phar --version

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: GPG sign phar file (detached)
        run: |
          echo "${{ secrets.GPG_PASSPHRASE }}" | \
          gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --detach-sign -a \
          -o n98-magerun2.phar.asc n98-magerun2.phar
        env:
          GPG_TTY: $(tty)

      - name: GPG verify phar file
        run: gpg --verify n98-magerun2.phar.asc n98-magerun2.phar

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: n98-magerun2.phar
          path: |
            n98-magerun2.phar
            n98-magerun2.phar.asc

  update-files-magerun-net:
    runs-on: ubuntu-latest
    needs: ["create-signed-phar-file"]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: n98-magerun2.phar
          path: .

      - name: rename phar file (deploy test)
        if: github.ref == 'refs/heads/deploy'
        run: |
          mv n98-magerun2.phar n98-magerun2-deploy.phar
          mv n98-magerun2.phar.asc n98-magerun2-deploy.phar.asc
          ls -l

      - name: rename phar file (develop / unstable)
        if: github.ref == 'refs/heads/develop'
        run: |
          mv n98-magerun2.phar n98-magerun2-dev.phar
          mv n98-magerun2.phar.asc n98-magerun2-dev.phar.asc
          ls -l

      - name: rename phar file (tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # get tag part of github.ref
          TAG=$(cut -d'/' -f3 <<< "$GITHUB_REF")
          cp n98-magerun2.phar n98-magerun2-${TAG}.phar
          cp n98-magerun2.phar.asc n98-magerun2-${TAG}.phar.asc
          mv n98-magerun2.phar n98-magerun2-latest.phar
          mv n98-magerun2.phar.asc n98-magerun2-latest.phar.asc
          ls -l

      - name: Upload phar file to ssh remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_DEPLOY_HOST }}
          username: ${{ secrets.SSH_DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_DEPLOY_PASSPHRASE }}
          source: '*.phar,*.phar.asc'
          target: ${{ secrets.SSH_DEPLOY_TARGET }}
          rm: false
          overwrite: true
