---
name: Deploy

on:
  push:
    branches:
      - develop
      - deploy
    tags:
      # only tags with semver format
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-signed-phar-file:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:2
          php-version: '7.4'

      - name: Checkout HEAD
        uses: actions/checkout@v3.6.0

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create phar
        run: bash ./build.sh

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: GPG sign phar file (detached)
        run: |
          echo "${{ secrets.GPG_PASSPHRASE }}" | \
          gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --detach-sign -a \
          -o n98-magerun2.phar.asc n98-magerun2.phar
        env:
          GPG_TTY: $(tty)

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: n98-magerun2.phar
          path: |
            n98-magerun2.phar
            n98-magerun2.phar.asc

  update-files-magerun-net:
    runs-on: ubuntu-latest
    needs: ["create-signed-phar-file"]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: n98-magerun2.phar
          path: .
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:2
          php-version: '7.4'
      - name: Run phar file
        run: php n98-magerun2.phar --version

